-- Code generated by cloudflare/d1/tools/generate-ent-baseline.mjs. DO NOT EDIT.
-- Source: legacy/backend/ent/migrate/schema.go
-- Source SHA-256: 742164d3fec0f80c2c952bfa44128240365c1088e3d07a69cef2ef2450461084
-- Ent tables: 38; columns: 600; indexes: 140; foreign keys: 35
-- Scope excludes supplemental raw-SQL tables listed in ../supplemental-tables.md.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "api_keys" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "key" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "last_used_at" TEXT,
    "ip_whitelist" TEXT,
    "ip_blacklist" TEXT,
    "quota" REAL NOT NULL DEFAULT 0,
    "quota_used" REAL NOT NULL DEFAULT 0,
    "expires_at" TEXT,
    "rate_limit_5h" REAL NOT NULL DEFAULT 0,
    "rate_limit_1d" REAL NOT NULL DEFAULT 0,
    "rate_limit_7d" REAL NOT NULL DEFAULT 0,
    "usage_5h" REAL NOT NULL DEFAULT 0,
    "usage_1d" REAL NOT NULL DEFAULT 0,
    "usage_7d" REAL NOT NULL DEFAULT 0,
    "window_5h_start" TEXT,
    "window_1d_start" TEXT,
    "window_7d_start" TEXT,
    "group_id" INTEGER,
    "user_id" INTEGER NOT NULL,
    CONSTRAINT "api_keys_groups_api_keys" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE SET NULL,
    CONSTRAINT "api_keys_users_api_keys" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "accounts" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "name" TEXT NOT NULL,
    "notes" TEXT,
    "platform" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "credentials" TEXT NOT NULL,
    "extra" TEXT NOT NULL,
    "proxy_fallback_origin_id" INTEGER,
    "concurrency" INTEGER NOT NULL DEFAULT 3,
    "load_factor" INTEGER,
    "priority" INTEGER NOT NULL DEFAULT 50,
    "rate_multiplier" REAL NOT NULL DEFAULT 1,
    "status" TEXT NOT NULL DEFAULT 'active',
    "error_message" TEXT,
    "last_used_at" TEXT,
    "expires_at" TEXT,
    "auto_pause_on_expired" INTEGER NOT NULL DEFAULT 1,
    "schedulable" INTEGER NOT NULL DEFAULT 1,
    "rate_limited_at" TEXT,
    "rate_limit_reset_at" TEXT,
    "overload_until" TEXT,
    "temp_unschedulable_until" TEXT,
    "temp_unschedulable_reason" TEXT,
    "session_window_start" TEXT,
    "session_window_end" TEXT,
    "session_window_status" TEXT,
    "quota_dimension" TEXT NOT NULL DEFAULT 'global' CHECK ("quota_dimension" IN ('global', 'spark')),
    "proxy_id" INTEGER,
    "parent_account_id" INTEGER,
    CONSTRAINT "accounts_proxies_proxy" FOREIGN KEY ("proxy_id") REFERENCES "proxies" ("id") ON DELETE SET NULL,
    CONSTRAINT "accounts_accounts_children" FOREIGN KEY ("parent_account_id") REFERENCES "accounts" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "account_groups" (
    "priority" INTEGER NOT NULL DEFAULT 50,
    "created_at" TEXT NOT NULL,
    "account_id" INTEGER NOT NULL,
    "group_id" INTEGER NOT NULL,
    PRIMARY KEY ("account_id", "group_id"),
    CONSTRAINT "account_groups_accounts_account" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON DELETE NO ACTION,
    CONSTRAINT "account_groups_groups_group" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "announcements" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "notify_mode" TEXT NOT NULL DEFAULT 'silent',
    "targeting" TEXT,
    "starts_at" TEXT,
    "ends_at" TEXT,
    "created_by" INTEGER,
    "updated_by" INTEGER,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "announcement_reads" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "read_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "announcement_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    CONSTRAINT "announcement_reads_announcements_reads" FOREIGN KEY ("announcement_id") REFERENCES "announcements" ("id") ON DELETE NO ACTION,
    CONSTRAINT "announcement_reads_users_announcement_reads" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "auth_identities" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "provider_type" TEXT NOT NULL,
    "provider_key" TEXT NOT NULL,
    "provider_subject" TEXT NOT NULL,
    "verified_at" TEXT,
    "issuer" TEXT,
    "metadata" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    CONSTRAINT "auth_identities_users_auth_identities" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "auth_identity_channels" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "provider_type" TEXT NOT NULL,
    "provider_key" TEXT NOT NULL,
    "channel" TEXT NOT NULL,
    "channel_app_id" TEXT NOT NULL,
    "channel_subject" TEXT NOT NULL,
    "metadata" TEXT NOT NULL,
    "identity_id" INTEGER NOT NULL,
    CONSTRAINT "auth_identity_channels_auth_identities_channels" FOREIGN KEY ("identity_id") REFERENCES "auth_identities" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "batch_image_events" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "job_id" TEXT NOT NULL,
    "event_type" TEXT NOT NULL,
    "payload" TEXT,
    "event_hash" TEXT,
    "created_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "batch_image_items" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "job_id" TEXT NOT NULL,
    "custom_id" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "request_hash" TEXT,
    "prompt_preview" TEXT,
    "provider_source_object" TEXT,
    "source_line_number" INTEGER,
    "source_byte_offset" INTEGER,
    "source_byte_length" INTEGER,
    "mime_type" TEXT,
    "file_extension" TEXT,
    "image_count" INTEGER NOT NULL DEFAULT 0,
    "error_code" TEXT,
    "error_message" TEXT,
    "billed_amount" REAL,
    "created_at" TEXT NOT NULL,
    "indexed_at" TEXT
);

CREATE TABLE IF NOT EXISTS "batch_image_jobs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "batch_id" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "api_key_id" INTEGER,
    "account_id" INTEGER,
    "provider" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "task_name" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'created',
    "provider_job_name" TEXT,
    "provider_input_ref" TEXT,
    "provider_output_ref" TEXT,
    "gcs_input_uri" TEXT,
    "gcs_output_uri" TEXT,
    "item_count" INTEGER NOT NULL,
    "success_count" INTEGER NOT NULL DEFAULT 0,
    "fail_count" INTEGER NOT NULL DEFAULT 0,
    "cancelled_count" INTEGER NOT NULL DEFAULT 0,
    "estimated_cost" REAL NOT NULL DEFAULT 0,
    "hold_amount" REAL,
    "actual_cost" REAL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "hold_id" TEXT,
    "idempotency_key" TEXT,
    "request_hash" TEXT,
    "manifest_hash" TEXT,
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 0,
    "output_expires_at" TEXT,
    "input_deleted_at" TEXT,
    "output_deleted_at" TEXT,
    "downloaded_at" TEXT,
    "user_deleted_at" TEXT,
    "last_error_code" TEXT,
    "last_error_message" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "submitted_at" TEXT,
    "started_at" TEXT,
    "finished_at" TEXT,
    "settled_at" TEXT
);

CREATE TABLE IF NOT EXISTS "channel_monitors" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "provider" TEXT NOT NULL CHECK ("provider" IN ('openai', 'anthropic', 'gemini', 'grok')),
    "api_mode" TEXT NOT NULL DEFAULT 'chat_completions',
    "endpoint" TEXT NOT NULL,
    "api_key_encrypted" TEXT NOT NULL,
    "primary_model" TEXT NOT NULL,
    "extra_models" TEXT NOT NULL,
    "group_name" TEXT DEFAULT '',
    "enabled" INTEGER NOT NULL DEFAULT 1,
    "interval_seconds" INTEGER NOT NULL,
    "jitter_seconds" INTEGER NOT NULL DEFAULT 0,
    "last_checked_at" TEXT,
    "created_by" INTEGER NOT NULL,
    "extra_headers" TEXT NOT NULL,
    "body_override_mode" TEXT NOT NULL DEFAULT 'off',
    "body_override" TEXT,
    "template_id" INTEGER,
    CONSTRAINT "channel_monitors_channel_monitor_request_templates_request_template" FOREIGN KEY ("template_id") REFERENCES "channel_monitor_request_templates" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "channel_monitor_daily_rollups" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "model" TEXT NOT NULL,
    "bucket_date" TEXT NOT NULL,
    "total_checks" INTEGER NOT NULL DEFAULT 0,
    "ok_count" INTEGER NOT NULL DEFAULT 0,
    "operational_count" INTEGER NOT NULL DEFAULT 0,
    "degraded_count" INTEGER NOT NULL DEFAULT 0,
    "failed_count" INTEGER NOT NULL DEFAULT 0,
    "error_count" INTEGER NOT NULL DEFAULT 0,
    "sum_latency_ms" INTEGER NOT NULL DEFAULT 0,
    "count_latency" INTEGER NOT NULL DEFAULT 0,
    "sum_ping_latency_ms" INTEGER NOT NULL DEFAULT 0,
    "count_ping_latency" INTEGER NOT NULL DEFAULT 0,
    "computed_at" TEXT NOT NULL,
    "monitor_id" INTEGER NOT NULL,
    CONSTRAINT "channel_monitor_daily_rollups_channel_monitors_daily_rollups" FOREIGN KEY ("monitor_id") REFERENCES "channel_monitors" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "channel_monitor_histories" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "model" TEXT NOT NULL,
    "status" TEXT NOT NULL CHECK ("status" IN ('operational', 'degraded', 'failed', 'error')),
    "latency_ms" INTEGER,
    "ping_latency_ms" INTEGER,
    "message" TEXT DEFAULT '',
    "checked_at" TEXT NOT NULL,
    "monitor_id" INTEGER NOT NULL,
    CONSTRAINT "channel_monitor_histories_channel_monitors_history" FOREIGN KEY ("monitor_id") REFERENCES "channel_monitors" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "channel_monitor_request_templates" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "provider" TEXT NOT NULL CHECK ("provider" IN ('openai', 'anthropic', 'gemini', 'grok')),
    "api_mode" TEXT NOT NULL DEFAULT 'chat_completions',
    "description" TEXT DEFAULT '',
    "extra_headers" TEXT NOT NULL,
    "body_override_mode" TEXT NOT NULL DEFAULT 'off',
    "body_override" TEXT
);

CREATE TABLE IF NOT EXISTS "error_passthrough_rules" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "enabled" INTEGER NOT NULL DEFAULT 1,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "error_codes" TEXT,
    "keywords" TEXT,
    "match_mode" TEXT NOT NULL DEFAULT 'any',
    "platforms" TEXT,
    "passthrough_code" INTEGER NOT NULL DEFAULT 1,
    "response_code" INTEGER,
    "passthrough_body" INTEGER NOT NULL DEFAULT 1,
    "custom_message" TEXT,
    "skip_monitoring" INTEGER NOT NULL DEFAULT 0,
    "description" TEXT
);

CREATE TABLE IF NOT EXISTS "groups" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "rate_multiplier" REAL NOT NULL DEFAULT 1,
    "peak_rate_enabled" INTEGER NOT NULL DEFAULT 0,
    "peak_start" TEXT NOT NULL DEFAULT '',
    "peak_end" TEXT NOT NULL DEFAULT '',
    "peak_rate_multiplier" REAL NOT NULL DEFAULT 1,
    "is_exclusive" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'active',
    "platform" TEXT NOT NULL DEFAULT 'anthropic',
    "subscription_type" TEXT NOT NULL DEFAULT 'standard',
    "daily_limit_usd" REAL,
    "weekly_limit_usd" REAL,
    "monthly_limit_usd" REAL,
    "default_validity_days" INTEGER NOT NULL DEFAULT 30,
    "allow_image_generation" INTEGER NOT NULL DEFAULT 0,
    "allow_batch_image_generation" INTEGER NOT NULL DEFAULT 0,
    "image_rate_independent" INTEGER NOT NULL DEFAULT 0,
    "image_rate_multiplier" REAL NOT NULL DEFAULT 1,
    "image_price_1k" REAL,
    "image_price_2k" REAL,
    "image_price_4k" REAL,
    "batch_image_discount_multiplier" REAL NOT NULL DEFAULT 0.5,
    "batch_image_hold_multiplier" REAL NOT NULL DEFAULT 0.6,
    "video_rate_independent" INTEGER NOT NULL DEFAULT 0,
    "video_rate_multiplier" REAL NOT NULL DEFAULT 1,
    "video_price_480p" REAL,
    "video_price_720p" REAL,
    "video_price_1080p" REAL,
    "web_search_price_per_call" REAL,
    "claude_code_only" INTEGER NOT NULL DEFAULT 0,
    "fallback_group_id" INTEGER,
    "fallback_group_id_on_invalid_request" INTEGER,
    "model_routing" TEXT,
    "model_routing_enabled" INTEGER NOT NULL DEFAULT 0,
    "mcp_xml_inject" INTEGER NOT NULL DEFAULT 1,
    "supported_model_scopes" TEXT NOT NULL,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "allow_messages_dispatch" INTEGER NOT NULL DEFAULT 0,
    "require_oauth_only" INTEGER NOT NULL DEFAULT 0,
    "require_privacy_set" INTEGER NOT NULL DEFAULT 0,
    "default_mapped_model" TEXT NOT NULL DEFAULT '',
    "messages_dispatch_model_config" TEXT NOT NULL,
    "models_list_config" TEXT NOT NULL,
    "rpm_limit" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "idempotency_records" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "idempotency_key_hash" TEXT NOT NULL,
    "request_fingerprint" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "response_status" INTEGER,
    "response_body" TEXT,
    "error_reason" TEXT,
    "locked_until" TEXT,
    "expires_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "identity_adoption_decisions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "adopt_display_name" INTEGER NOT NULL DEFAULT 0,
    "adopt_avatar" INTEGER NOT NULL DEFAULT 0,
    "decided_at" TEXT NOT NULL,
    "identity_id" INTEGER,
    "pending_auth_session_id" INTEGER NOT NULL UNIQUE,
    CONSTRAINT "identity_adoption_decisions_auth_identities_adoption_decisions" FOREIGN KEY ("identity_id") REFERENCES "auth_identities" ("id") ON DELETE SET NULL,
    CONSTRAINT "identity_adoption_decisions_pending_auth_sessions_adoption_decision" FOREIGN KEY ("pending_auth_session_id") REFERENCES "pending_auth_sessions" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "payment_audit_logs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "order_id" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "detail" TEXT NOT NULL DEFAULT '',
    "operator" TEXT NOT NULL DEFAULT 'system',
    "created_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "payment_orders" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "user_email" TEXT NOT NULL,
    "user_name" TEXT NOT NULL,
    "user_notes" TEXT,
    "amount" REAL NOT NULL,
    "pay_amount" REAL NOT NULL,
    "fee_rate" REAL NOT NULL DEFAULT 0,
    "recharge_code" TEXT NOT NULL,
    "out_trade_no" TEXT NOT NULL DEFAULT '',
    "payment_type" TEXT NOT NULL,
    "payment_trade_no" TEXT NOT NULL,
    "pay_url" TEXT,
    "qr_code" TEXT,
    "qr_code_img" TEXT,
    "order_type" TEXT NOT NULL DEFAULT 'balance',
    "plan_id" INTEGER,
    "subscription_group_id" INTEGER,
    "subscription_days" INTEGER,
    "provider_instance_id" TEXT,
    "provider_key" TEXT,
    "provider_snapshot" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "refund_amount" REAL NOT NULL DEFAULT 0,
    "refund_reason" TEXT,
    "refund_at" TEXT,
    "force_refund" INTEGER NOT NULL DEFAULT 0,
    "refund_requested_at" TEXT,
    "refund_request_reason" TEXT,
    "refund_requested_by" TEXT,
    "expires_at" TEXT NOT NULL,
    "paid_at" TEXT,
    "completed_at" TEXT,
    "failed_at" TEXT,
    "failed_reason" TEXT,
    "client_ip" TEXT NOT NULL,
    "src_host" TEXT NOT NULL,
    "src_url" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    CONSTRAINT "payment_orders_users_payment_orders" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "payment_provider_instances" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "provider_key" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    "config" TEXT NOT NULL,
    "supported_types" TEXT NOT NULL DEFAULT '',
    "enabled" INTEGER NOT NULL DEFAULT 1,
    "payment_mode" TEXT NOT NULL DEFAULT '',
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "limits" TEXT NOT NULL DEFAULT '',
    "refund_enabled" INTEGER NOT NULL DEFAULT 0,
    "allow_user_refund" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "pending_auth_sessions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "session_token" TEXT NOT NULL,
    "intent" TEXT NOT NULL,
    "provider_type" TEXT NOT NULL,
    "provider_key" TEXT NOT NULL,
    "provider_subject" TEXT NOT NULL,
    "redirect_to" TEXT NOT NULL DEFAULT '',
    "resolved_email" TEXT NOT NULL DEFAULT '',
    "registration_password_hash" TEXT NOT NULL DEFAULT '',
    "upstream_identity_claims" TEXT NOT NULL,
    "local_flow_state" TEXT NOT NULL,
    "browser_session_key" TEXT NOT NULL DEFAULT '',
    "completion_code_hash" TEXT NOT NULL DEFAULT '',
    "completion_code_expires_at" TEXT,
    "email_verified_at" TEXT,
    "password_verified_at" TEXT,
    "totp_verified_at" TEXT,
    "expires_at" TEXT NOT NULL,
    "consumed_at" TEXT,
    "target_user_id" INTEGER,
    CONSTRAINT "pending_auth_sessions_users_pending_auth_sessions" FOREIGN KEY ("target_user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "promo_codes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "code" TEXT NOT NULL UNIQUE,
    "bonus_amount" REAL NOT NULL DEFAULT 0,
    "max_uses" INTEGER NOT NULL DEFAULT 0,
    "used_count" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'active',
    "expires_at" TEXT,
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "promo_code_usages" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "bonus_amount" REAL NOT NULL,
    "used_at" TEXT NOT NULL,
    "promo_code_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    CONSTRAINT "promo_code_usages_promo_codes_usage_records" FOREIGN KEY ("promo_code_id") REFERENCES "promo_codes" ("id") ON DELETE NO ACTION,
    CONSTRAINT "promo_code_usages_users_promo_code_usages" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "proxies" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "name" TEXT NOT NULL,
    "protocol" TEXT NOT NULL,
    "host" TEXT NOT NULL,
    "port" INTEGER NOT NULL,
    "username" TEXT,
    "password" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "expires_at" TEXT,
    "fallback_mode" TEXT NOT NULL DEFAULT 'none',
    "expiry_warn_days" INTEGER NOT NULL DEFAULT 7,
    "backup_proxy_id" INTEGER UNIQUE,
    CONSTRAINT "proxies_proxies_backup_proxy" FOREIGN KEY ("backup_proxy_id") REFERENCES "proxies" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "redeem_codes" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "code" TEXT NOT NULL UNIQUE,
    "type" TEXT NOT NULL DEFAULT 'balance',
    "value" REAL NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'unused',
    "used_at" TEXT,
    "notes" TEXT,
    "created_at" TEXT NOT NULL,
    "expires_at" TEXT,
    "validity_days" INTEGER NOT NULL DEFAULT 30,
    "group_id" INTEGER,
    "used_by" INTEGER,
    CONSTRAINT "redeem_codes_groups_redeem_codes" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE SET NULL,
    CONSTRAINT "redeem_codes_users_redeem_codes" FOREIGN KEY ("used_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "security_secrets" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "key" TEXT NOT NULL UNIQUE,
    "value" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "settings" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "key" TEXT NOT NULL UNIQUE,
    "value" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "subscription_plans" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "group_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "price" REAL NOT NULL,
    "original_price" REAL,
    "validity_days" INTEGER NOT NULL DEFAULT 30,
    "validity_unit" TEXT NOT NULL DEFAULT 'day',
    "features" TEXT NOT NULL DEFAULT '',
    "product_name" TEXT NOT NULL DEFAULT '',
    "for_sale" INTEGER NOT NULL DEFAULT 1,
    "sort_order" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "tls_fingerprint_profiles" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT,
    "enable_grease" INTEGER NOT NULL DEFAULT 0,
    "cipher_suites" TEXT,
    "curves" TEXT,
    "point_formats" TEXT,
    "signature_algorithms" TEXT,
    "alpn_protocols" TEXT,
    "supported_versions" TEXT,
    "key_share_groups" TEXT,
    "psk_modes" TEXT,
    "extensions" TEXT
);

CREATE TABLE IF NOT EXISTS "usage_cleanup_tasks" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "filters" TEXT NOT NULL,
    "created_by" INTEGER NOT NULL,
    "deleted_rows" INTEGER NOT NULL DEFAULT 0,
    "error_message" TEXT,
    "canceled_by" INTEGER,
    "canceled_at" TEXT,
    "started_at" TEXT,
    "finished_at" TEXT
);

CREATE TABLE IF NOT EXISTS "usage_logs" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "request_id" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "requested_model" TEXT,
    "upstream_model" TEXT,
    "channel_id" INTEGER,
    "model_mapping_chain" TEXT,
    "billing_tier" TEXT,
    "billing_mode" TEXT,
    "input_tokens" INTEGER NOT NULL DEFAULT 0,
    "output_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_creation_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_read_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_creation_5m_tokens" INTEGER NOT NULL DEFAULT 0,
    "cache_creation_1h_tokens" INTEGER NOT NULL DEFAULT 0,
    "input_cost" REAL NOT NULL DEFAULT 0,
    "output_cost" REAL NOT NULL DEFAULT 0,
    "cache_creation_cost" REAL NOT NULL DEFAULT 0,
    "cache_read_cost" REAL NOT NULL DEFAULT 0,
    "total_cost" REAL NOT NULL DEFAULT 0,
    "actual_cost" REAL NOT NULL DEFAULT 0,
    "rate_multiplier" REAL NOT NULL DEFAULT 1,
    "long_context_billing_applied" INTEGER NOT NULL DEFAULT 0,
    "account_rate_multiplier" REAL,
    "billing_type" INTEGER NOT NULL DEFAULT 0,
    "stream" INTEGER NOT NULL DEFAULT 0,
    "duration_ms" INTEGER,
    "first_token_ms" INTEGER,
    "user_agent" TEXT,
    "ip_address" TEXT,
    "image_count" INTEGER NOT NULL DEFAULT 0,
    "image_size" TEXT,
    "image_input_size" TEXT,
    "image_output_size" TEXT,
    "image_size_source" TEXT,
    "image_size_breakdown" TEXT,
    "video_count" INTEGER NOT NULL DEFAULT 0,
    "video_resolution" TEXT,
    "video_duration_seconds" INTEGER,
    "cache_ttl_overridden" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL,
    "api_key_id" INTEGER NOT NULL,
    "account_id" INTEGER NOT NULL,
    "group_id" INTEGER,
    "user_id" INTEGER NOT NULL,
    "subscription_id" INTEGER,
    CONSTRAINT "usage_logs_api_keys_usage_logs" FOREIGN KEY ("api_key_id") REFERENCES "api_keys" ("id") ON DELETE NO ACTION,
    CONSTRAINT "usage_logs_accounts_usage_logs" FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") ON DELETE NO ACTION,
    CONSTRAINT "usage_logs_groups_usage_logs" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE SET NULL,
    CONSTRAINT "usage_logs_users_usage_logs" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION,
    CONSTRAINT "usage_logs_user_subscriptions_usage_logs" FOREIGN KEY ("subscription_id") REFERENCES "user_subscriptions" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "email" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "balance" REAL NOT NULL DEFAULT 0,
    "frozen_balance" REAL NOT NULL DEFAULT 0,
    "concurrency" INTEGER NOT NULL DEFAULT 5,
    "status" TEXT NOT NULL DEFAULT 'active',
    "username" TEXT NOT NULL DEFAULT '',
    "notes" TEXT NOT NULL DEFAULT '',
    "totp_secret_encrypted" TEXT,
    "totp_enabled" INTEGER NOT NULL DEFAULT 0,
    "totp_enabled_at" TEXT,
    "signup_source" TEXT NOT NULL DEFAULT 'email',
    "last_login_at" TEXT,
    "last_active_at" TEXT,
    "balance_notify_enabled" INTEGER NOT NULL DEFAULT 1,
    "balance_notify_threshold_type" TEXT NOT NULL DEFAULT 'fixed',
    "balance_notify_threshold" REAL,
    "balance_notify_extra_emails" TEXT NOT NULL DEFAULT '[]',
    "total_recharged" REAL NOT NULL DEFAULT 0,
    "rpm_limit" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "user_allowed_groups" (
    "created_at" TEXT NOT NULL,
    "user_id" INTEGER NOT NULL,
    "group_id" INTEGER NOT NULL,
    PRIMARY KEY ("user_id", "group_id"),
    CONSTRAINT "user_allowed_groups_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION,
    CONSTRAINT "user_allowed_groups_groups_group" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "user_attribute_definitions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "type" TEXT NOT NULL,
    "options" TEXT NOT NULL,
    "required" INTEGER NOT NULL DEFAULT 0,
    "validation" TEXT NOT NULL,
    "placeholder" TEXT NOT NULL DEFAULT '',
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "enabled" INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "user_attribute_values" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "value" TEXT NOT NULL DEFAULT '',
    "user_id" INTEGER NOT NULL,
    "attribute_id" INTEGER NOT NULL,
    CONSTRAINT "user_attribute_values_users_attribute_values" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION,
    CONSTRAINT "user_attribute_values_user_attribute_definitions_values" FOREIGN KEY ("attribute_id") REFERENCES "user_attribute_definitions" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "user_platform_quotas" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "platform" TEXT NOT NULL,
    "daily_limit_usd" REAL,
    "weekly_limit_usd" REAL,
    "monthly_limit_usd" REAL,
    "daily_usage_usd" REAL NOT NULL DEFAULT 0,
    "weekly_usage_usd" REAL NOT NULL DEFAULT 0,
    "monthly_usage_usd" REAL NOT NULL DEFAULT 0,
    "daily_window_start" TEXT,
    "weekly_window_start" TEXT,
    "monthly_window_start" TEXT,
    "user_id" INTEGER NOT NULL,
    CONSTRAINT "user_platform_quotas_users_platform_quotas" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "user_subscriptions" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    "deleted_at" TEXT,
    "starts_at" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "daily_window_start" TEXT,
    "weekly_window_start" TEXT,
    "monthly_window_start" TEXT,
    "daily_usage_usd" REAL NOT NULL DEFAULT 0,
    "weekly_usage_usd" REAL NOT NULL DEFAULT 0,
    "monthly_usage_usd" REAL NOT NULL DEFAULT 0,
    "assigned_at" TEXT NOT NULL,
    "notes" TEXT,
    "group_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "assigned_by" INTEGER,
    CONSTRAINT "user_subscriptions_groups_subscriptions" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE NO ACTION,
    CONSTRAINT "user_subscriptions_users_subscriptions" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION,
    CONSTRAINT "user_subscriptions_users_assigned_subscriptions" FOREIGN KEY ("assigned_by") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "apikey_user_id" ON "api_keys" ("user_id");
CREATE INDEX IF NOT EXISTS "apikey_group_id" ON "api_keys" ("group_id");
CREATE INDEX IF NOT EXISTS "apikey_status" ON "api_keys" ("status");
CREATE INDEX IF NOT EXISTS "apikey_deleted_at" ON "api_keys" ("deleted_at");
CREATE INDEX IF NOT EXISTS "apikey_last_used_at" ON "api_keys" ("last_used_at");
CREATE INDEX IF NOT EXISTS "apikey_quota_quota_used" ON "api_keys" ("quota", "quota_used");
CREATE INDEX IF NOT EXISTS "apikey_expires_at" ON "api_keys" ("expires_at");
CREATE INDEX IF NOT EXISTS "account_platform" ON "accounts" ("platform");
CREATE INDEX IF NOT EXISTS "account_type" ON "accounts" ("type");
CREATE INDEX IF NOT EXISTS "account_status" ON "accounts" ("status");
CREATE INDEX IF NOT EXISTS "account_proxy_id" ON "accounts" ("proxy_id");
CREATE INDEX IF NOT EXISTS "account_priority" ON "accounts" ("priority");
CREATE INDEX IF NOT EXISTS "account_last_used_at" ON "accounts" ("last_used_at");
CREATE INDEX IF NOT EXISTS "account_schedulable" ON "accounts" ("schedulable");
CREATE INDEX IF NOT EXISTS "account_rate_limited_at" ON "accounts" ("rate_limited_at");
CREATE INDEX IF NOT EXISTS "account_rate_limit_reset_at" ON "accounts" ("rate_limit_reset_at");
CREATE INDEX IF NOT EXISTS "account_overload_until" ON "accounts" ("overload_until");
CREATE INDEX IF NOT EXISTS "account_platform_priority" ON "accounts" ("platform", "priority");
CREATE INDEX IF NOT EXISTS "account_priority_status" ON "accounts" ("priority", "status");
CREATE INDEX IF NOT EXISTS "account_deleted_at" ON "accounts" ("deleted_at");
CREATE INDEX IF NOT EXISTS "account_parent_account_id" ON "accounts" ("parent_account_id");
CREATE INDEX IF NOT EXISTS "accountgroup_group_id" ON "account_groups" ("group_id");
CREATE INDEX IF NOT EXISTS "accountgroup_priority" ON "account_groups" ("priority");
CREATE INDEX IF NOT EXISTS "announcement_status" ON "announcements" ("status");
CREATE INDEX IF NOT EXISTS "announcement_created_at" ON "announcements" ("created_at");
CREATE INDEX IF NOT EXISTS "announcement_starts_at" ON "announcements" ("starts_at");
CREATE INDEX IF NOT EXISTS "announcement_ends_at" ON "announcements" ("ends_at");
CREATE INDEX IF NOT EXISTS "announcementread_announcement_id" ON "announcement_reads" ("announcement_id");
CREATE INDEX IF NOT EXISTS "announcementread_user_id" ON "announcement_reads" ("user_id");
CREATE INDEX IF NOT EXISTS "announcementread_read_at" ON "announcement_reads" ("read_at");
CREATE UNIQUE INDEX IF NOT EXISTS "announcementread_announcement_id_user_id" ON "announcement_reads" ("announcement_id", "user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "authidentity_provider_type_provider_key_provider_subject" ON "auth_identities" ("provider_type", "provider_key", "provider_subject");
CREATE INDEX IF NOT EXISTS "authidentity_user_id" ON "auth_identities" ("user_id");
CREATE INDEX IF NOT EXISTS "authidentity_user_id_provider_type" ON "auth_identities" ("user_id", "provider_type");
CREATE UNIQUE INDEX IF NOT EXISTS "authidentitychannel_provider_type_provider_key_channel_channel_app_id_channel_subject" ON "auth_identity_channels" ("provider_type", "provider_key", "channel", "channel_app_id", "channel_subject");
CREATE INDEX IF NOT EXISTS "authidentitychannel_identity_id" ON "auth_identity_channels" ("identity_id");
CREATE INDEX IF NOT EXISTS "batchimageevent_job_id_created_at" ON "batch_image_events" ("job_id", "created_at");
CREATE INDEX IF NOT EXISTS "batchimageevent_event_type" ON "batch_image_events" ("event_type");
CREATE UNIQUE INDEX IF NOT EXISTS "batchimageevent_job_id_event_hash" ON "batch_image_events" ("job_id", "event_hash") WHERE event_hash IS NOT NULL AND event_hash <> '';
CREATE UNIQUE INDEX IF NOT EXISTS "batchimageitem_job_id_custom_id" ON "batch_image_items" ("job_id", "custom_id");
CREATE INDEX IF NOT EXISTS "batchimageitem_job_id_status" ON "batch_image_items" ("job_id", "status");
CREATE INDEX IF NOT EXISTS "batchimageitem_provider_source_object" ON "batch_image_items" ("provider_source_object");
CREATE UNIQUE INDEX IF NOT EXISTS "batchimagejob_batch_id" ON "batch_image_jobs" ("batch_id");
CREATE INDEX IF NOT EXISTS "batchimagejob_user_id_created_at" ON "batch_image_jobs" ("user_id", "created_at");
CREATE INDEX IF NOT EXISTS "batchimagejob_status" ON "batch_image_jobs" ("status");
CREATE INDEX IF NOT EXISTS "batchimagejob_provider_status" ON "batch_image_jobs" ("provider", "status");
CREATE INDEX IF NOT EXISTS "batchimagejob_idempotency_key" ON "batch_image_jobs" ("idempotency_key") WHERE idempotency_key IS NOT NULL AND idempotency_key <> '';
CREATE UNIQUE INDEX IF NOT EXISTS "batchimagejob_manifest_hash" ON "batch_image_jobs" ("manifest_hash") WHERE manifest_hash IS NOT NULL AND manifest_hash <> '';
CREATE INDEX IF NOT EXISTS "batchimagejob_output_expires_at" ON "batch_image_jobs" ("output_expires_at");
CREATE INDEX IF NOT EXISTS "batchimagejob_downloaded_at" ON "batch_image_jobs" ("downloaded_at");
CREATE INDEX IF NOT EXISTS "batchimagejob_user_deleted_at" ON "batch_image_jobs" ("user_deleted_at");
CREATE INDEX IF NOT EXISTS "channelmonitor_enabled_last_checked_at" ON "channel_monitors" ("enabled", "last_checked_at");
CREATE INDEX IF NOT EXISTS "channelmonitor_provider" ON "channel_monitors" ("provider");
CREATE INDEX IF NOT EXISTS "channelmonitor_provider_api_mode" ON "channel_monitors" ("provider", "api_mode");
CREATE INDEX IF NOT EXISTS "channelmonitor_group_name" ON "channel_monitors" ("group_name");
CREATE INDEX IF NOT EXISTS "channelmonitor_template_id" ON "channel_monitors" ("template_id");
CREATE UNIQUE INDEX IF NOT EXISTS "channelmonitordailyrollup_monitor_id_model_bucket_date" ON "channel_monitor_daily_rollups" ("monitor_id", "model", "bucket_date");
CREATE INDEX IF NOT EXISTS "channelmonitordailyrollup_bucket_date" ON "channel_monitor_daily_rollups" ("bucket_date");
CREATE INDEX IF NOT EXISTS "channelmonitorhistory_monitor_id_model_checked_at" ON "channel_monitor_histories" ("monitor_id", "model", "checked_at");
CREATE INDEX IF NOT EXISTS "channelmonitorhistory_checked_at" ON "channel_monitor_histories" ("checked_at");
CREATE UNIQUE INDEX IF NOT EXISTS "channelmonitorrequesttemplate_provider_name" ON "channel_monitor_request_templates" ("provider", "name");
CREATE INDEX IF NOT EXISTS "channelmonitorrequesttemplate_provider_api_mode" ON "channel_monitor_request_templates" ("provider", "api_mode");
CREATE INDEX IF NOT EXISTS "errorpassthroughrule_enabled" ON "error_passthrough_rules" ("enabled");
CREATE INDEX IF NOT EXISTS "errorpassthroughrule_priority" ON "error_passthrough_rules" ("priority");
CREATE INDEX IF NOT EXISTS "group_status" ON "groups" ("status");
CREATE INDEX IF NOT EXISTS "group_platform" ON "groups" ("platform");
CREATE INDEX IF NOT EXISTS "group_subscription_type" ON "groups" ("subscription_type");
CREATE INDEX IF NOT EXISTS "group_is_exclusive" ON "groups" ("is_exclusive");
CREATE INDEX IF NOT EXISTS "group_deleted_at" ON "groups" ("deleted_at");
CREATE INDEX IF NOT EXISTS "group_sort_order" ON "groups" ("sort_order");
CREATE UNIQUE INDEX IF NOT EXISTS "idempotencyrecord_scope_idempotency_key_hash" ON "idempotency_records" ("scope", "idempotency_key_hash");
CREATE INDEX IF NOT EXISTS "idempotencyrecord_expires_at" ON "idempotency_records" ("expires_at");
CREATE INDEX IF NOT EXISTS "idempotencyrecord_status_locked_until" ON "idempotency_records" ("status", "locked_until");
CREATE UNIQUE INDEX IF NOT EXISTS "identityadoptiondecision_pending_auth_session_id" ON "identity_adoption_decisions" ("pending_auth_session_id");
CREATE INDEX IF NOT EXISTS "identityadoptiondecision_identity_id" ON "identity_adoption_decisions" ("identity_id");
CREATE INDEX IF NOT EXISTS "paymentauditlog_order_id" ON "payment_audit_logs" ("order_id");
CREATE UNIQUE INDEX IF NOT EXISTS "paymentorder_out_trade_no" ON "payment_orders" ("out_trade_no") WHERE out_trade_no <> '';
CREATE INDEX IF NOT EXISTS "paymentorder_user_id" ON "payment_orders" ("user_id");
CREATE INDEX IF NOT EXISTS "paymentorder_status" ON "payment_orders" ("status");
CREATE INDEX IF NOT EXISTS "paymentorder_expires_at" ON "payment_orders" ("expires_at");
CREATE INDEX IF NOT EXISTS "paymentorder_created_at" ON "payment_orders" ("created_at");
CREATE INDEX IF NOT EXISTS "paymentorder_paid_at" ON "payment_orders" ("paid_at");
CREATE INDEX IF NOT EXISTS "paymentorder_payment_type_paid_at" ON "payment_orders" ("payment_type", "paid_at");
CREATE INDEX IF NOT EXISTS "paymentorder_order_type" ON "payment_orders" ("order_type");
CREATE INDEX IF NOT EXISTS "paymentproviderinstance_provider_key" ON "payment_provider_instances" ("provider_key");
CREATE INDEX IF NOT EXISTS "paymentproviderinstance_enabled" ON "payment_provider_instances" ("enabled");
CREATE UNIQUE INDEX IF NOT EXISTS "pendingauthsession_session_token" ON "pending_auth_sessions" ("session_token");
CREATE INDEX IF NOT EXISTS "pendingauthsession_target_user_id" ON "pending_auth_sessions" ("target_user_id");
CREATE INDEX IF NOT EXISTS "pendingauthsession_expires_at" ON "pending_auth_sessions" ("expires_at");
CREATE INDEX IF NOT EXISTS "pendingauthsession_provider_type_provider_key_provider_subject" ON "pending_auth_sessions" ("provider_type", "provider_key", "provider_subject");
CREATE INDEX IF NOT EXISTS "pendingauthsession_completion_code_hash" ON "pending_auth_sessions" ("completion_code_hash");
CREATE INDEX IF NOT EXISTS "promocode_status" ON "promo_codes" ("status");
CREATE INDEX IF NOT EXISTS "promocode_expires_at" ON "promo_codes" ("expires_at");
CREATE INDEX IF NOT EXISTS "promocodeusage_promo_code_id" ON "promo_code_usages" ("promo_code_id");
CREATE INDEX IF NOT EXISTS "promocodeusage_user_id" ON "promo_code_usages" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "promocodeusage_promo_code_id_user_id" ON "promo_code_usages" ("promo_code_id", "user_id");
CREATE INDEX IF NOT EXISTS "proxy_status" ON "proxies" ("status");
CREATE INDEX IF NOT EXISTS "proxy_deleted_at" ON "proxies" ("deleted_at");
CREATE INDEX IF NOT EXISTS "proxy_expires_at" ON "proxies" ("expires_at");
CREATE INDEX IF NOT EXISTS "proxy_backup_proxy_id" ON "proxies" ("backup_proxy_id");
CREATE INDEX IF NOT EXISTS "redeemcode_status" ON "redeem_codes" ("status");
CREATE INDEX IF NOT EXISTS "redeemcode_used_by" ON "redeem_codes" ("used_by");
CREATE INDEX IF NOT EXISTS "redeemcode_group_id" ON "redeem_codes" ("group_id");
CREATE INDEX IF NOT EXISTS "redeemcode_expires_at" ON "redeem_codes" ("expires_at");
CREATE INDEX IF NOT EXISTS "subscriptionplan_group_id" ON "subscription_plans" ("group_id");
CREATE INDEX IF NOT EXISTS "subscriptionplan_for_sale" ON "subscription_plans" ("for_sale");
CREATE INDEX IF NOT EXISTS "usagecleanuptask_status_created_at" ON "usage_cleanup_tasks" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "usagecleanuptask_created_at" ON "usage_cleanup_tasks" ("created_at");
CREATE INDEX IF NOT EXISTS "usagecleanuptask_canceled_at" ON "usage_cleanup_tasks" ("canceled_at");
CREATE INDEX IF NOT EXISTS "usagelog_user_id" ON "usage_logs" ("user_id");
CREATE INDEX IF NOT EXISTS "usagelog_api_key_id" ON "usage_logs" ("api_key_id");
CREATE INDEX IF NOT EXISTS "usagelog_account_id" ON "usage_logs" ("account_id");
CREATE INDEX IF NOT EXISTS "usagelog_group_id" ON "usage_logs" ("group_id");
CREATE INDEX IF NOT EXISTS "usagelog_subscription_id" ON "usage_logs" ("subscription_id");
CREATE INDEX IF NOT EXISTS "usagelog_created_at" ON "usage_logs" ("created_at");
CREATE INDEX IF NOT EXISTS "usagelog_model" ON "usage_logs" ("model");
CREATE INDEX IF NOT EXISTS "usagelog_requested_model" ON "usage_logs" ("requested_model");
CREATE INDEX IF NOT EXISTS "usagelog_request_id" ON "usage_logs" ("request_id");
CREATE INDEX IF NOT EXISTS "usagelog_user_id_created_at" ON "usage_logs" ("user_id", "created_at");
CREATE INDEX IF NOT EXISTS "usagelog_api_key_id_created_at" ON "usage_logs" ("api_key_id", "created_at");
CREATE INDEX IF NOT EXISTS "usagelog_group_id_created_at" ON "usage_logs" ("group_id", "created_at");
CREATE INDEX IF NOT EXISTS "user_status" ON "users" ("status");
CREATE INDEX IF NOT EXISTS "user_deleted_at" ON "users" ("deleted_at");
CREATE INDEX IF NOT EXISTS "userallowedgroup_group_id" ON "user_allowed_groups" ("group_id");
CREATE INDEX IF NOT EXISTS "userattributedefinition_key" ON "user_attribute_definitions" ("key");
CREATE INDEX IF NOT EXISTS "userattributedefinition_enabled" ON "user_attribute_definitions" ("enabled");
CREATE INDEX IF NOT EXISTS "userattributedefinition_display_order" ON "user_attribute_definitions" ("display_order");
CREATE INDEX IF NOT EXISTS "userattributedefinition_deleted_at" ON "user_attribute_definitions" ("deleted_at");
CREATE UNIQUE INDEX IF NOT EXISTS "userattributevalue_user_id_attribute_id" ON "user_attribute_values" ("user_id", "attribute_id");
CREATE INDEX IF NOT EXISTS "userattributevalue_attribute_id" ON "user_attribute_values" ("attribute_id");
CREATE UNIQUE INDEX IF NOT EXISTS "userplatformquota_user_id_platform" ON "user_platform_quotas" ("user_id", "platform") WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS "userplatformquota_user_id" ON "user_platform_quotas" ("user_id");
CREATE INDEX IF NOT EXISTS "usersubscription_user_id" ON "user_subscriptions" ("user_id");
CREATE INDEX IF NOT EXISTS "usersubscription_group_id" ON "user_subscriptions" ("group_id");
CREATE INDEX IF NOT EXISTS "usersubscription_status" ON "user_subscriptions" ("status");
CREATE INDEX IF NOT EXISTS "usersubscription_expires_at" ON "user_subscriptions" ("expires_at");
CREATE INDEX IF NOT EXISTS "usersubscription_user_id_status_expires_at" ON "user_subscriptions" ("user_id", "status", "expires_at");
CREATE INDEX IF NOT EXISTS "usersubscription_assigned_by" ON "user_subscriptions" ("assigned_by");
CREATE INDEX IF NOT EXISTS "usersubscription_user_id_group_id" ON "user_subscriptions" ("user_id", "group_id");
CREATE INDEX IF NOT EXISTS "usersubscription_deleted_at" ON "user_subscriptions" ("deleted_at");
